### ISSUE TITLE
Spaces in JSON appear to break request

### ISSUE THREAD

**Issue by eddible** [adnanh/webhook#585]
Hey,
I'm trying to use the entire-payload option, passing the JSON in a POST request into a Python script but I keep getting errors because there are spaces in some of the JSON Values. If I pass it to my JSON script, the JSON loads function complains of it being badly formatted, and if you print it back, it's only looking up to "Edward " - it seems that first space breaks it. 

Here's the JSON sent as a POST request:

```
{
  "version": "1.0.0",
  "workflow_id": "workflow_45dd8e6683234ba8a7de0f7762a1920b",
  "event": {
    "date_triggered": "2022-04-12T17:39:02.622Z",
    "event_types": [
      "audit_updated"
    ],
    "triggered_by": {
      "type": "user",
      "user": "user_57562cd48c1649438421d849bfff99cf",
      "name": "Edward Ab"
    }
  },
  "data": {
    "audit": {
      "template_id": "template_478a72fea2174bf0a6347eb48bc7cd93",
      "audit_id": "audit_4b1c799dd62649279b6233ac2b4d21b4",
      "archived": false,
      "created_at": "2022-04-12T17:18:58.122Z",
      "modified_at": "2022-04-12T17:39:02.552Z",
      "audit_data": {
        "score": 1,
        "total_score": 121,
        "score_percentage": 0.826,
        "name": "",
        "duration": 1201,
        "authorship": {
          "device_id": "user_57562cd48c1649438421d849bfff99cf",
          "owner": "Edward Ab",
          "owner_id": "user_57562cd48c1649438421d849bfff99cf",
          "author": "Edward Ab",
          "author_id": "user_57562cd48c1649438421d849bfff99cf"
        },
        "date_completed": null,
        "date_modified": null,
        "date_started": null
      },
      "template_data": {
        "authorship": {
          "device_id": "user_57562cd48c1649438421d849bfff99cf",
          "owner": "Edward Ab",
          "owner_id": "user_57562cd48c1649438421d849bfff99cf",
          "author": "Edward Ab",
          "author_id": "user_57562cd48c1649438421d849bfff99cf"
        },
        "metadata": {
          "description": "",
          "name": "Edd Test (Do not edit)"
        }
      },
      "header_items": [
        {
          "item_id": "f3245d39-ea77-11e1-aff1-0800200c9a66",
          "label": "Title Page",
          "type": "section",
          "scoring": {
            "combined_max_score": 121,
            "combined_score": 1,
            "combined_score_percentage": 0.826
          },
          "children": [
            "04385108-0604-4e21-a221-2b9c57b40eac",
            "140f34b4-ded9-426c-b886-903bc46e5fc6"
          ]
        },
        {
          "parent_id": "f3245d39-ea77-11e1-aff1-0800200c9a66",
          "item_id": "04385108-0604-4e21-a221-2b9c57b40eac",
          "label": "Z Axis",
          "type": "slider",
          "scoring": {
            "max_score": 120,
            "score": 1,
            "score_percentage": 0.833
          },
          "options": {
            "weighting": 1,
            "increment": 1,
            "max": 120,
            "min": 1,
            "is_mandatory": false
          },
          "responses": {
            "value": 1
          }
        },
        {
          "parent_id": "f3245d39-ea77-11e1-aff1-0800200c9a66",
          "item_id": "140f34b4-ded9-426c-b886-903bc46e5fc6",
          "label": "Gripper",
          "type": "checkbox",
          "scoring": {
            "max_score": 1,
            "score": 0,
            "score_percentage": 0
          },
          "options": {
            "weighting": 1,
            "is_mandatory": false
          }
        }
      ]
    },
    "template": {
      "template_id": "template_478a72fea2174bf0a6347eb48bc7cd93",
      "name": "Edd Test (Do not edit)"
    }
  }
}
```

I want the entire JSON doc to come across into my Python script. My hooks.json looks like this:

```
[
{
    "id": "receive_inspection",
    "execute-command": "/home/pi/docker/code/workspace/pybot/webhook/process-inspection.sh",
    "command-working-directory": "/home/pi/docker/code/workspace/pybot",
    "include-command-output-in-response": true,
    "pass-arguments-to-command":
    [
      {
        "source": "entire-payload"
      }
    ]
 }
]
```

and my sh script:
```
#!/bin/sh

python3 process-inspection.py $1
```

I'm wondering if it's something in my sh script as that's the part I'm least familiar with but I'm not too sure where to go from here. I also tried to using:

```
      {
        "source": "payload",
        "name": "data"
      }
```

but the returning data is formatted with "map" all through it, rather than as JSON.

Is this a bug or am I missing something?

**Comment by eddible** [comment]
Here's what I get in my terminal:

```
executing /home/pi/docker/code/workspace/pybot/webhook/process-inspection.sh (/home/pi/docker/code/workspace/pybot/webhook/process-inspection.sh) with arguments ["/home/pi/docker/code/workspace/pybot/webhook/process-inspection.sh" "{\"data\":{\"audit\":{\"archived\":false,\"audit_data\":{\"authorship\":{\"author\":\"Edward Ab\",\"author_id\":\"user_57562cd48c1649438421d849bfff99cf\",\"device_id\":\"user_57562cd48c1649438421d849bfff99cf\",\"owner\":\"Edward Ab\",\"owner_id\":\"user_57562cd48c1649438421d849bfff99cf\"},\"date_completed\":null,\"date_modified\":null,\"date_started\":null,\"duration\":1201,\"name\":\"\",\"score\":1,\"score_percentage\":0.826,\"total_score\":121},\"audit_id\":\"audit_4b1c799dd62649279b6233ac2b4d21b4\",\"created_at\":\"2022-04-12T17:18:58.122Z\",\"header_items\":[{\"children\":[\"04385108-0604-4e21-a221-2b9c57b40eac\",\"140f34b4-ded9-426c-b886-903bc46e5fc6\"],\"item_id\":\"f3245d39-ea77-11e1-aff1-0800200c9a66\",\"label\":\"Title Page\",\"scoring\":{\"combined_max_score\":121,\"combined_score\":1,\"combined_score_percentage\":0.826},\"type\":\"section\"},{\"item_id\":\"04385108-0604-4e21-a221-2b9c57b40eac\",\"label\":\"Z Axis\",\"options\":{\"increment\":1,\"is_mandatory\":false,\"max\":120,\"min\":1,\"weighting\":1},\"parent_id\":\"f3245d39-ea77-11e1-aff1-0800200c9a66\",\"responses\":{\"value\":1},\"scoring\":{\"max_score\":120,\"score\":1,\"score_percentage\":0.833},\"type\":\"slider\"},{\"item_id\":\"140f34b4-ded9-426c-b886-903bc46e5fc6\",\"label\":\"Gripper\",\"options\":{\"is_mandatory\":false,\"weighting\":1},\"parent_id\":\"f3245d39-ea77-11e1-aff1-0800200c9a66\",\"scoring\":{\"max_score\":1,\"score\":0,\"score_percentage\":0},\"type\":\"checkbox\"}],\"modified_at\":\"2022-04-12T17:39:02.552Z\",\"template_data\":{\"authorship\":{\"author\":\"Edward Ab\",\"author_id\":\"user_57562cd48c1649438421d849bfff99cf\",\"device_id\":\"user_57562cd48c1649438421d849bfff99cf\",\"owner\":\"Edward Ab\",\"owner_id\":\"user_57562cd48c1649438421d849bfff99cf\"},\"metadata\":{\"description\":\"\",\"name\":\"Edd Test (Do not edit)\"}},\"template_id\":\"template_478a72fea2174bf0a6347eb48bc7cd93\"},\"template\":{\"name\":\"Edd Test (Do not edit)\",\"template_id\":\"template_478a72fea2174bf0a6347eb48bc7cd93\"}},\"event\":{\"date_triggered\":\"2022-04-12T17:39:02.622Z\",\"event_types\":[\"audit_updated\"],\"triggered_by\":{\"name\":\"Edward Ab\",\"type\":\"user\",\"user\":\"user_57562cd48c1649438421d849bfff99cf\"}},\"version\":\"1.0.0\",\"workflow_id\":\"workflow_45dd8e6683234ba8a7de0f7762a1920b\"}"] and environment [] using /home/pi/docker/code/workspace/pybot as cwd
[webhook] 2022/04/13 10:06:22 [3bd0d9] command output: {"data":{"audit":{"archived":false,"audit_data":{"authorship":{"author":"Edward
Traceback (most recent call last):
  File "/home/pi/docker/code/workspace/pybot/process-inspection.py", line 5, in <module>
    audit_json = json.loads(sys.argv[1])
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 73 (char 72)
```

**Comment by eddible** [comment]
Ha I've been pouring over this for hours and obviously the moment I raise the issue I fix it. If anyone comes across this, in the sh script, you need quotes around the variable, like this:
```
#!/bin/sh

python3 process-inspection.py "$1"
```
